language: node_js
node_js:
  - 12 # uses version 12
services:
  - postgresql # starts up postgres
addons:
  postgresql: '10' # recent postgres version on Travis
dist: xenial # uses xenial environment
notifications:
  email:
    on_success: change # default: change (only when going from broken to fixed)
    on_failure: always # default: always (which is annoying, as it should be)
install:
  - npm ci # faster, goes only from package-lock
before_script:
  - psql -c 'create database "adminpage";' -U postgres # remember to change this name if you change it elsewhere (e.g. package.json)
script:
  - npm run build-client # make the bundle
before_deploy: # omit node_modules, since we set skip_cleanup below
  - rm -rf node_modules
deploy: # see README for details on these keys
  # prevents travis from deleting the build
  skip_cleanup: true
  provider: heroku
  # app should be your heroku app name; see README
  app: carrectlyadminofficial
  # the secure key indicates an encrypted value; see README
  api_key:
    secure: KczHcltCOTe9RbV0vL0sH+OFUKjQoUxc6bTcw9Gj+F7TtC9GBC7wMOZ92V2Kka3yZBuXz0/n9iYlWs9DJahus8fgT2A+43FCixjCrKILE+GqdSkycg/EewRNGvx+a+zJnLDIiwVErxuDmBVmuaGNGCu9nnihWAVD1/5/FbvERiPc77CDOk5XfR71vTl4aE+pyWKMpg8LnK64aCURj8ZfQUujxgOCRjjCEqXP/JFviRlNvU205qTanKaOq8WyWLsPoOwC+xUIZZCjUoU2fge8QSV+qrAoRngKbafgb1bFXz8pNNE73O9o5a0IKqQYzQ91AUAD062u+xxZlb36KFp8w7WyzpxNZMMOxeH+859jx3z+M7uJIPchRA3Iqj0a2eUblgVQIxYYZr40vbL1bBkZMUkRxJs/knflwXX3EnlUKS1rB9nVPEzKYwFiyhnBNlSgAzapHKZlt86DkOnkahCPXcABBSX1HZaFoVtQq4OrSjjHX44dPIDtNI0ZvLp8kMZQfGLK1sLwVjJuxXiEkwcrr4ETF08YQEbnt1YY9DJHTajrLFIV4Oi0jO22d8k2bcSoQAx5xVRjXhQYbGCSB8G5hkwf6vRTmJ5NO8gYKnqr2OTtVtlYGLFDW8ge32E8vNtkES4kr6izR13nsyo6kRLhZ/Aej2nyDZ8pAC46QnZtBJc=
