language: node_js
node_js:
  - 16 # uses version 12
services:
  - postgresql # starts up postgres
addons:
  postgresql: '13.5' # recent postgres version on Travis
dist: xenial # uses xenial environment
notifications:
  email:
    on_success: change # default: change (only when going from broken to fixed)
    on_failure: always # default: always (which is annoying, as it should be)
install:
  - npm ci # faster, goes only from package-lock
before_script:
  - psql -c 'create database "adminpage";' -U postgres # remember to change this name if you change it elsewhere (e.g. package.json)
script:
  - npm run build-client # make the bundle
before_deploy: # omit node_modules, since we set skip_cleanup below
  - rm -rf node_modules
deploy: # see README for details on these keys
  # prevents travis from deleting the build
  skip_cleanup: true
  provider: heroku
  # app should be your heroku app name; see README
  app: carrectly-admin-staging
  # the secure key indicates an encrypted value; see README
  api_key:
    secure: Bgy5atg7wIwMbcf8Slf6TsvwFyW0jUF0dvO/U3vuciLmUjAtSPnxxF61pL0FAFT5XBRzeLidnplubcdOwgpPrNNZ7pd8txL90uGGvLnjEiFuxw5fE2K/QZCq7LMiQJ1N/fNP1Gn430BaNW8hjf0DaVz9MEjNTOgsjdqpp9IeEVZ6Zr/gqs18/EOR2pGbpoHbhbW65B439kJiISMnKpD92k/Ix0iKSBGYcWBQmKMP9NehYtD4Dx1qK0WDCioUEMJ0POTeE/CT+gR5HVZawyq3gCAJN4+TBM9LGE9HU7T2iW04pTHjjl8cAdH0xF/M1ZyADXt/GaiDc8ogIToapGffLlkWtBOwT3UMlulILsT0TE93J5Gqgn+2uXuT3QY4Rt8dGKjbRFZ/XZOBn1gW0R4zqL4xeWUm/7t2ocj73fil5y/fwZSQNwyND4do20cjJ2NAR92Q27hiIn2uFlhAdDIVlug20k6lpMnZ0by6Vj8PnBweudGw5t/GkgAk6oLmG3lUGzGwxQ848fEXOdCPJJARXhe2nVm30wZDCJiASA3JxaWD0S9nXxortvNOY/Y/GaFMxrExclBqpMtc1YlDKFWZlPHyYZYaWwrciKkiJEnXfH/CYuudE7vpXsc+62pK5UqXWTnF8JIx3jnFv9l0SvS8plp7URZDnqBEQknsoUT9o/w=
