language: node_js
node_js:
  - 12 # uses version 12
services:
  - postgresql # starts up postgres
addons:
  postgresql: '10' # recent postgres version on Travis
dist: xenial # uses xenial environment
notifications:
  email:
    on_success: change # default: change (only when going from broken to fixed)
    on_failure: always # default: always (which is annoying, as it should be)
install:
  - npm ci # faster, goes only from package-lock
before_script:
  - psql -c 'create database "adminpage";' -U postgres # remember to change this name if you change it elsewhere (e.g. package.json)
script:
  - npm run build-client # make the bundle
before_deploy: # omit node_modules, since we set skip_cleanup below
  - rm -rf node_modules
deploy: # see README for details on these keys
  # prevents travis from deleting the build
  skip_cleanup: true
  provider: heroku
  # app should be your heroku app name; see README
  app: carrectlyadminofficial
  # the secure key indicates an encrypted value; see README
  api_key:
    secure: bfsbBN7/RU63UMAuq/I8y9Szs9X3VYjS1X4E+s99rGqtXMdb3x23cfCICr4HsZOI/rg9UihXQ/rT32g5cEW+0td9m+KS7YgcDHFVZNik7w7LXvUNtu1H6RqGYn5TNZU3EkHpST9UYgGo5PoJGXvt+ajP+o9cMDGHJf+XJcO2UbZ6ud+WJ6WqoQRTpz7U0ehcsKSwjIDk+S7Psmu7R0mdxy20s5hdtOVBMpE8akcFPtUXZfAzQzlEnZhsGhV4hAC9miDPzawkIsw++HsospmIBuzVTaIKpKaqV3Ye/bq0dePUUhfMQFZLjyfGz0CHmW9eHDv81nVQoNH4HwQB7sV0tN5BtzXs0tCkXCfyg0hvqbpSYCCz8bzFda5qBJou8sB1x4WQGU8F9VucN9BhGu+iIBs5bHRm1oRoa7Xay/irP31+Q0EVjDnNTi/TsZmSyIYL51DbCxhKDICUFV6sHdp615VlqKdDp24L+CkHBvhOuwkdjC9UphiP1K8S3wSCrgypzCfo00OOB+yVfvcM8ppi37VMTmvneNElFoJ4sngFQ8v63NPnrL3fdmzk1RI6cPdVIz7pIQKWx13dAhdlt3F2Yyg/H0HeK2zI07JO+RoNy/qzkcGfptAP7Dq4pu9h+Nezg0/1MU61mSacJj5PLyb942zwCaEPm3x2KnYdpJG3KfM=
