language: node_js
node_js:
  - 16 # uses version 12
services:
  - postgresql # starts up postgres
addons:
  postgresql: '10' # recent postgres version on Travis
dist: xenial # uses xenial environment
notifications:
  email:
    on_success: change # default: change (only when going from broken to fixed)
    on_failure: always # default: always (which is annoying, as it should be)
install:
  - npm ci # faster, goes only from package-lock
before_script:
  - psql -c 'create database "adminpage";' -U postgres # remember to change this name if you change it elsewhere (e.g. package.json)
script:
  - npm run build:prod # make the bundle
before_deploy: # omit node_modules, since we set skip_cleanup below
  - rvm $(travis_internal_ruby) --fuzzy do ruby -S gem install faraday -v 1.9.3
  - rm -rf node_modules
deploy: # see README for details on these keys
  # prevents travis from deleting the build
  skip_cleanup: true
  provider: heroku
  # app should be your heroku app name; see README
  app: carrectly-admin-staging
  # the secure key indicates an encrypted value; see README
  api_key:
    secure: OQgNLNt5bgiCwAhiF4ekg+6KATuJ1tI7DYgkHzXs5f8/JLbA6yKmGtBMDMcickOB1ZEwysyV/IcXnJpi5V1WFhklc5iUB5O7nYn5gX/N4qwrRHVp6YaX+qkqqFr9Dbt4dl2Z+chDWy7fgYTeKswXwrrEZXG1YI7a/ymDOqrElZj74E2IIsKzstJMvU1Cjg2aufR0oKgwcBBDkUZj3eKzm98WuErc1397vp0Q6NEwBd+7KlSHh1Pt2se4BlsoAXdSgFpCQo3Wz3ue7p1uKfw/DjYMTZoEWoyr0cfmIZjtL/uo8Yn4TkuZ4WfFgazW9iL7uqAHVl+cfrrgk1a30jpfyA4+u1IvP5NMOafdbq0JgBfFjkbZQxF2l/CzWiikXZoYTNKoq+AW6PBAGH7S+E8Bqr7bw0wRcBHrvcXjstjoo3WUDctiIkH/1HCg99lLytn2c2tA7iVX5FZVxGq/qBcyubLD8Zs9lPXSC/9QtE0vmZg6BOSlliWOP9YFPzG9wXjLlScju2Ggh5eAcdb5RP2U2EOA6ohUFV1wWq1kJgBcKdyglCw6j90nOj74MefVbSr//X0xw8/FwJK5ypi2QrLJiUpO3cRxTh7dFbvmxHUVnt5hXOAcYnyIoJptwTWDV9I/Hu4EEjGVaTzNFqeX0GwdRz3wJ+1l0VwDS+VooD5eEJQ=
