language: node_js
node_js:
  - 16 # uses version 12
services:
  - postgresql # starts up postgres
addons:
  postgresql: '10' # recent postgres version on Travis
dist: xenial # uses xenial environment
notifications:
  email:
    on_success: change # default: change (only when going from broken to fixed)
    on_failure: always # default: always (which is annoying, as it should be)
install:
  - npm ci # faster, goes only from package-lock
before_script:
  - psql -c 'create database "adminpage";' -U postgres # remember to change this name if you change it elsewhere (e.g. package.json)
script:
  - npm run build-client # make the bundle
before_deploy: # omit node_modules, since we set skip_cleanup below
  - rm -rf node_modules
deploy: # see README for details on these keys
  # prevents travis from deleting the build
  skip_cleanup: true
  provider: heroku
  # app should be your heroku app name; see README
  app: carrectly-admin-staging
  # the secure key indicates an encrypted value; see README
  api_key: LAvRI/MbuJhTIaIqSYMd0d5RSKhCMnJKOiw6Q53nRjV3YPPiCXDjIpqNZngoYaq/4ZLTQPi2WlZMylQWTErgZy35meAjxl9YOleihuVQ246ZEf4R6p1hL4xNRMYe01lADF7BhlhLGwbd7UxaHwrWxTYlpwT5NYv8+IBWbTlajN+ehtULcOi7vWd9fzYSt4u2Eu7vpHjy1VmCW6UsfZVZuYEZjOT2VQjzjut7DNVrbQHfmKQdfT286ZGgdxMlNxVphx0YTSZvuCSSg5TW8Zwx+fZkddcXMQOFzIkJpHEf1ZeU5O1Vx2P9/GqSDWFCg5HSJXaiOLl/hjfOfKYdswzhePpr5Pe3HE8Ar9eGafbk05VZeuMNKwZTjHEtgzZjq5ptmwpXDWXceWmLSNhhIjRIME/MMSWStY3IRSQb2SWrUGmROobWE6c8jhTBg2BSUCeLd4HCBTsb/TNwv/hBpcYO0Blxc/amxlK34m0wj+zHev0E28BRZ3jrwiwDS7eR9G/40xVY44e0xo0sG0L6SlEXR0yEUHV+VQRUe/ZieG2E/+cfoESUj2hD9P8hkGNdSxNVHXzB0AJwltQ7yHvB7TYFBCCt8I0gjWivmEX1AZYIKqISIxNeuuZtGnTJiMGA1aMj2NyLIkUna7AJSaqnm9wvRnYqHUt782xaXPCtV1gYuyA=
