language: node_js
node_js:
  - 12 # uses version 12
services:
  - postgresql # starts up postgres
addons:
  postgresql: '10' # recent postgres version on Travis
dist: xenial # uses xenial environment
notifications:
  email:
    on_success: change # default: change (only when going from broken to fixed)
    on_failure: always # default: always (which is annoying, as it should be)
install:
  - npm ci # faster, goes only from package-lock
before_script:
  - psql -c 'create database "adminpage";' -U postgres # remember to change this name if you change it elsewhere (e.g. package.json)
script:
  - npm run build-client # make the bundle
before_deploy: # omit node_modules, since we set skip_cleanup below
  - rm -rf node_modules
deploy: # see README for details on these keys
  # prevents travis from deleting the build
  skip_cleanup: true
  provider: heroku
  # app should be your heroku app name; see README
  app: carrectlyadminofficial
  # the secure key indicates an encrypted value; see README
  api_key:
    secure: S2LVx4GxwH3iLkCtpgvE8kvc9451ecEkwoI6dkM0dL81CMlMj5NzvCCweomupqqtSBDYIXQUsCOO8TugeERERX1rjsm2yyZJ3erQKtEzsrATRLsEOBJsk8riN7ZIF6FRCZDMmC5YIGyAT7sNVsJ7lrDz84x3BVAm+1phUtAdJPKPi4pUrfKlPg9PPw4QFhGJ0qRzOjwiGbcqN6Qp0uu9byr6Amh+VWVt8SUGNmCKQc47tTsLMJ87gkbycoku5WXj4fA7gbAIyu6XSmulnT2MaessTAJXcyAy8YChcLN+Yd4+qzkKLR7NEPQCkWErfjg6eGaAs4jwFuCK/PdKhTOiLm5IdRxTid2SxruBRNhiaUZUNgmLjExSem9S2J76kifmlLTZCqY9ArRTeQVoK3+YuHMBd6DE5yRrhZf6qnBjtwDIhskS9LqRGJDMWrsfH+OEcA9bwMMYeoGkKCzE6ZhU4dQV+c07hea0LMCKkSkejrRfQGJOZf3/jYbQclMOziapXATpGYT7bpDIePjZdfILQcK2OVR3kEe3vLGLApnbjFwbJ5r5vFYoxufUlh9IvwEEfa/PxQsLk6TIUz0x3ZbcqptN6EPs/7y1/8BHHuQMTEKndXhzW4rXsXlDY2LbF9HinbfI474/gViUJVY2M6ObdN01T27ro+ir5H+8pmObMOc=
