language: node_js
node_js:
  - 16 # uses version 12
services:
  - postgresql # starts up postgres
addons:
  postgresql: '10' # recent postgres version on Travis
dist: xenial # uses xenial environment
notifications:
  email:
    on_success: change # default: change (only when going from broken to fixed)
    on_failure: always # default: always (which is annoying, as it should be)
install:
  - npm ci # faster, goes only from package-lock
before_script:
  - psql -c 'create database "adminpage";' -U postgres # remember to change this name if you change it elsewhere (e.g. package.json)
script:
  - npm run build-client # make the bundle
before_deploy: # omit node_modules, since we set skip_cleanup below
  - rm -rf node_modules
deploy: # see README for details on these keys
  # prevents travis from deleting the build
  skip_cleanup: true
  provider: heroku
  # app should be your heroku app name; see README
  app: carrectly-admin-staging
  # the secure key indicates an encrypted value; see README
  api_key:
    secure: AyboT8Sumct9yuoax0XdWnpA/gVDGA+wnqFh897MlFyFedYIv0EsF12hDl1yWOABBlxnoJFQ1IXC7NaqRK4Pzr1U+Ub8TZjz7Efqexv3HjH5r0xcY2R76CeBsfnWAyl7nCCBaK9WAkFDLbvY+AkFecJfAjRDmNsEt7+6qlWiM6e8jS4SBV6BeJ8ZeDfppYrz+wPoAVyCc2sran+xdzRlSQIJIPHSUSbfm/L2Q4fjkMsTA0A+zj6sycoMcGvCZ+vOh2k78Bt7Yb5DiP9Lsa8dxpqx/k0AvJa0uqgOd3snxo9pZYzXquZPaMtpgqIF1e2z4GbJJpWoCCKW5qAlPHy2Ey9S0TUNT081bnD0OkYC/OB05Ac+9GzLqQyCpgeONENbX35u+yiLEuF5ULbFY3KA341bLGpnpmNxT6RIRLf4JbkAJsaYgqIMqVmFcAmX/hdiR/hR0heHBEWJj5iPKfjWWEPACsj+pQaUl6+2STYLeYqxGdyq/g+MIs1FwNu62BMzYslp/slsJqmCvZdSWhxDHcDD7U8QjGApp+Fz8NilhZ+4etkzCNRtIoeXw1VIUfsrGjl2BsRoWLF4cy/OhmVwxzYp6s/kcRdiDEa7vdXjTWGsPXSoGGSo28jhp6EqlyTZEnvQb11g7lKWzqtykxR15wkexSIxxuUpaEBhCNPmanI=
